services:
  zapohteh_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ${COMPOSE_PROJECT_NAME}
    ports:
      - "8014:8014"
    environment:
      - DB_PATH=${DB_PATH:-/app/data/app.db}
      - STATIC_PATH=web/dist
      - CONTENT_DIR=/app/data
    networks:
      - app-network
    volumes:
      - .:/app
      - ${HOST_DATA_PATH:-./data}:/app/data

networks:
  app-network:
    driver: bridge
